export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const PRODUCTS_FETCH = 'PRODUCTS_FETCH';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_ERROR = 'PRODUCTS_FETCH_ERROR';

export const PRODUCTS_DELETE = 'PRODUCTS_DELETE';
export const PRODUCTS_DELETE_SUCCESS = 'PRODUCTS_DELETE_SUCCESS';
export const PRODUCTS_DELETE_ERROR = 'PRODUCTS_DELETE_ERROR';

export const PRODUCTS_SET_EDIT = 'PRODUCTS_SET_EDIT';
export const PRODUCTS_EDIT = 'PRODUCTS_EDIT';
export const PRODUCTS_EDIT_SUCCESS = 'PRODUCTS_EDIT_SUCCESS';
export const PRODUCTS_EDIT_ERROR = 'PRODUCTS_EDIT_ERROR';
